services:
    postgres:
        image: postgres:16
        shm_size: 128mb
        env_file:
            - .env
        volumes:
            - ./.data:/var/lib/postgresql/data
        networks:
            nvideos_net:
                ipv4_address: 172.12.0.16

networks:
  nvideos_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.12.0.0/16